### ISSUE TITLE
Update Django package version

### ISSUE THREAD

**Issue by SlavomirMazurPantheon** [YangCatalog/yang-validator-extractor#102]
Current Django package installed is `Django>=2.1.9`. However, newer versions are available: [2.2.28](https://pypi.org/project/Django/2.2.28/), [3.2.14](https://pypi.org/project/Django/3.2.14/) or [4.0.6](https://pypi.org/project/Django/4.0.6/).
It might be necessary to check which version could be used and check whether existing functionality will no be broken by this update.

**Comment by richardzilincikPantheon** [comment]
Currently this requirements results in 3.2.14 being installed. This is alright, since 3.2 [is marked as a long term support release](https://www.djangoproject.com/download/#supported-versions) and will receive security fixes until April 2024. The version should be pinned however, to make sure a new version with backwards incompatibilities doesn't get installed.
The Ubuntu release used by the docker image will soon reach end of life, and python 3.6 no longer receives security fixes.

**Comment by richardzilincikPantheon** [comment]
#103
