### ISSUE TITLE
Error 500 when validating an import with revision-date

### ISSUE THREAD

**Issue by dperdices** [YangCatalog/yang-validator-extractor#84]
Hi,

Happy New Year!

As the title says, we had some issues with the online validator. When validating [draft-ietf-ccamp-flexigrid-tunnel-yang](https://datatracker.ietf.org/doc/draft-ietf-ccamp-flexigrid-tunnel-yang/), the online validator frontend just hangs and I can see in the browser DevTools that a request to the backend returned code 500.

Doing a further investigation, I just noticed that, when submitting the YANG code without the revision-date (see [https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-tunnel-yang/blob/master/ietf-flexi-grid-tunnel.yang#L9](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-tunnel-yang/blob/master/ietf-flexi-grid-tunnel.yang#L9)), the code gets validated. So my guess is that something is broken in the processing of the revision dates.

**Comment by SlavomirMazurPantheon** [comment]
Hello,

Thanks for reporting this issue. I just tried to reproduce this and also got an error. I'm going to try to fix this as soon as possible.

Regards,
Slavomir Mazur

**Comment by SlavomirMazurPantheon** [comment]
Hello again,

I was able to identify root cause of this problem.
In draft https://datatracker.ietf.org/doc/html/draft-ietf-ccamp-flexigrid-tunnel-yang-00#page-19 we can see following line:
```
<CODE BEGINS> file "ietf-flexi-grid-tunnel@2021-10-25.yang"
```
However, a few lines below we can see following code:
```
 revision "2021-10-20" {
   description
     "Initial Revision";
   reference
     "RFC XXXX: YANG data model for Flexi-Grid tunnels";
   // RFC Ed.: replace XXXX with actual RFC number, update date
   // information and remove this note
 }
```
**There is an inconsistency in revisions - 2021-10-25 vs 2021-10-20.**
Xym tool extracts file with name ietf-flexi-grid-tunnel@2021-10-25.yang, but pyang then raises an error, because revision defined in code is 2021-10-20.
This also fits in your investigation because if you try to validate only code of extracted module it works fine.

I am not sure if this should be handled by xym, pyang or creator of draft himself.
From YANG Catalog perspective I am going to fix 500 Internal Error and add some kind of information to the user that error occurred during validation.

Regards,
Slavomir Mazur
